language: node_js
node_js:
- '0.10'
deploy:
  provider: openshift
  user: cycloptivity@internode.on.net
  password:
    secure: NEuiReBD7vZkNF2Ligvd0FXhVIKs+UpmIvZ3EWoilFdNpMc+IAsMTcFhJE71CMyLiq1dYaPlmz2MMzcdCdWJLgiaWxc3ldiZuqlHQAmH+UXcaBWyAKah3FUYzNdIpwfXd3S1G6RHFtC8q/ywhjQffqSum3s1KvCGXeXEID6BlcDZzPK0SVD8fJhB5NokqvH39ZWLhy9Hrs0Ar6FjsufYvo6MkqMjbgTXztAxKGCMAftgBH0kO+kKTnAx8CpnZgE3N80xM6vkoTwFDeg0AXFjs3VUECmS1xZJX7z92LHuPLNbSbuCP72YOnmU7sNhO65QNlPeJsSmsmqCI9ClPMEQ7+P6TyNH5D9ga94ZM1kkUymLEiD2oRi3+djPkVaLZbvzztMcLUKTXAj0fw9yKvab35tYYYyU9a8DwN7EvWCxwdA2SAdbGpj5DePAo/ft7OBWpMAQvTZsWgtcgRpgjOtjEabTFcQUeb8nUlDeIOqlkIY2X02edzcIBsIGuhDAljwZAjwK/0bBYXKOhu0kXmg9lvOGvrWJYf5dhcR8bG4ubx2s54eNslZF+uS4G1gNY03FZVjKFaRRVzOacV2ZFr/5VkNC/ILDGg29VqA/6v051hOKaTCS1+2at8bzdHtRGRUFkGuoRdgJTJCEwNZDsaTDG8BGHukoq+EfRQXjUQlTDrU=
  app: willow
  domain: kahn
  on:
    repo: Kahn/willow
